apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: backups.resources.cattle.io
spec:
  group: resources.cattle.io
  names:
    kind: Backup
    plural: backups
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            encryptionConfigName:
              description: 'Name of secret containing the encryption config, must
                be in the namespace of the chart: cattle-resources-system'
              type: string
            resourceSetName:
              description: Name of resourceSet CR to use for backup, must be in the
                same namespace
              type: string
            retention:
              format: duration
              type: string
            schedule:
              description: Cron schedule for recurring backups
              type: string
            storageLocation:
              nullable: true
              properties:
                local:
                  type: string
                s3:
                  nullable: true
                  properties:
                    bucketName:
                      type: string
                    credentialSecretName:
                      type: string
                    endpoint:
                      type: string
                    endpointCA:
                      type: string
                    folder:
                      type: string
                    insecureTLSSkipVerify:
                      type: boolean
                    region:
                      type: string
                  type: object
              type: object
          required:
          - resourceSetName
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    type: string
                  lastUpdateTime:
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                type: object
              nullable: true
              type: array
            lastSnapshotTs:
              type: string
            nextSnapshotAt:
              type: string
            numSnapshots:
              type: integer
            observedGeneration:
              type: integer
            summary:
              type: string
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
