apiVersion: apps/v1 
kind: Deployment
metadata:
  name: backup-restore-operator
  namespace: {{ .Release.Namespace }}
  labels:
    resources.cattle.io/operator: backup-restore
spec:
  selector:
    matchLabels:
      resources.cattle.io/operator: backup-restore
  template:
    metadata:
      labels:
        resources.cattle.io/operator: backup-restore
    spec:
      serviceAccountName: backup-restore-operator-serviceaccount
      containers:
      - name: backup-restore-operator
        image: {{ template "system_default_registry" . }}{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        env:
        - name: CHART_NAMESPACE
          value: {{ .Release.Namespace }}
          {{- if .Values.pvc }}
        - name: DEFAULT_PVC_BACKUP_STORAGE_LOCATION
          value: {{ .Release.Name }}-pvc
          {{- end }}
          {{- if .Values.s3 }}
        - name: DEFAULT_S3_BACKUP_STORAGE_LOCATION
          value: {{ .Release.Name }}-s3
          {{- end }}
        {{- if .Values.pvc }}
        volumeMounts:
        - mountPath: "/var/lib/backups"
          name: pv-storage
      volumes:
        - name: pv-storage
          persistentVolumeClaim:
            claimName: {{ .Values.pvcName }}
          {{- end}}
    {{- with .Values.nodeSelector }}
    nodeSelector:
    {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
    affinity:
    {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
    tolerations:
    {{- toYaml . | nindent 8 }}
    {{- end }}
