{{- if .Values.s3 -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-s3
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- with .Values.s3}}
  {{if .credentialSecretName }}credentialSecretName: {{ .credentialSecretName }} {{- end }}
  region: {{ .region }}
  bucketName: {{ .bucketName }}
  {{if .folder }}folder: {{ .folder }} {{- end}}
  endpoint: {{ .endpoint }}
  {{ if .endpointCA -}}endpointCA: {{ .endpointCA }} {{- end }}
  {{ if .insecureTLSSkipVerify }}insecureTLSSkipVerify: {{ .insecureTLSSkipVerify }} {{- end}}
  {{- end}}
{{ end }}