pipeline:
  lint-charts:
    image: guangbo/chart-testing:v2.0.1-rancher1
    commands:
      - git remote add rancher-charts https://github.com/rancher/charts
      - git fetch rancher-charts master
      - ct lint --config test/ct.yaml
