apiVersion: v1
version: 0.1.0
description: Installs the CRDs for rancher-backup.
name: rancher-backup-crd
type: application
annotations:
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/release-name: rancher-backup-crd
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/namespace: cattle-resources-system
